#!/usr/bin/env bash
# scripts that displays information about subdomains

domain_info() {
    local domain="$1"
    local subdomain="$2"
    local line
    line=$(dig +short "$subdomain.$domain")
    if [ -z "$line" ]; then
        echo "The subdomain $subdomain does not have an associated IP address."
    else
        echo "The subdomain $subdomain is a A record and points to $line"
    fi
}

if [ "$#" -eq 1 ]; then
    domain="$1"
    domain_info "$domain" "www"
    domain_info "$domain" "lb-01"
    domain_info "$domain" "web-01"
    domain_info "$domain" "web-02"
elif [ "$#" -eq 2 ]; then
    domain="$1"
    subdomain="$2"
    domain_info "$domain" "$subdomain"
else
    echo "Usage: $0 <domain> [subdomain]"
fi
