#!/usr/bin/env bash
# configuring nginx to direct on another page
sudo apt-get update -y
sudo apt-get install nginx -y

echo 'Hello World!' | sudo tee /var/www/html/index.html

replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/sylvieshimwauwase permanent;"

sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
