#!/usr/bin/env bash
# configuring nginx to direct on another page
sudo apt-get update -y
sudo apt-get install nginx -y

echo 'Hello World!' | sudo tee /var/www/html/index.html > /dev/null

sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default

sudo service ngnix start
