#!/usr/bin/env bash
# configuring nginx to 404 error page
sudo apt-get update -y
sudo apt-get install nginx -y

echo 'Hello World!' | sudo tee /var/www/html/index.html

replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/sylvieshimwauwase permanent;"

sudo sed -i "s/server_name _;/$replace/" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$replace/" /etc/nginx/sites-enabled/default

sudo service nginx restart
