#!/usr/bin/env bash

# Ensure that the script is running as root (sudo)
if [ "$(id -u)" != "0" ]; then
  echo "Please run this script as root or using sudo."
  exit 1
fi

# Update package list and install HAProxy
apt-get -y update
apt-get -y install haproxy

# Define the HAProxy configuration
server_config="
frontend sylvieshimwauwase_frontend
    bind *:80
    mode http
    default_backend sylvieshimwauwase_backend
    timeout client 30s
    timeout connect 5s
    timeout server 30s

backend sylvieshimwauwase_backend
    balance roundrobin
    mode http
    timeout client 30s
    timeout server 30s
    server 305654-web-01 54.224.33.148:80 check
    server 305654-web-02 54.234.37.54:80 check
"

# Create the HAProxy configuration directory if it doesn't exist
config_dir="/etc/haproxy"
mkdir -p "$config_dir"

# Create the HAProxy configuration file if it doesn't exist
config_file="$config_dir/haproxy.cfg"
touch "$config_file"

# Write the HAProxy configuration to haproxy.cfg
echo "$server_config" > "$config_file"

# Enable HAProxy by editing the default configuration file
echo "ENABLED=1" > /etc/default/haproxy

# Check the HAProxy configuration for syntax errors
haproxy -c -f "$config_file"

# Restart HAProxy service to apply the changes
systemctl restart haproxy
