#!/usr/bin/env bash
# script that pings an IP address passed as argument

if [ $# -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

ip_address=$1

echo "Pinging $ip_address 5 times..."
ping -c 5 "$ip_address"
