#!/usr/bin/env bash
# Script to configure a container to run Nginx as the nginx
pkill apache2
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
